In [223]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import data

In [255]:


"""時系列データの作成関数"""
def make_dataset(low_data, n_prev=100):

    data, target = [], []
    # 25データずつ分割
    maxlen = 21

    for i in range(len(low_data)-maxlen):
        data.append(low_data[i:i + maxlen])
        target.append(low_data[i + maxlen])

    re_data = np.array(data).reshape(len(data), maxlen, 1)
    re_target = np.array(target).reshape(len(data), 1)

    return re_data, re_target

In [243]:
"""import data 仮で3次元データの作成"""
test_data = pd.DataFrame(np.random.randint(1,100, (21, 50)))
print(test_data.shape)
print(len(test_data))
test_data.head()

(21, 50)
21

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,43,73,28,41,30,57,64,29,61,26,...,90,25,43,71,84,17,54,20,31,35
1,88,67,92,62,14,73,59,64,29,36,...,60,54,1,84,39,72,60,63,24,74
2,63,68,96,2,60,61,54,57,69,99,...,74,6,91,83,8,69,55,54,97,64
3,79,20,44,64,23,95,51,41,12,6,...,1,79,36,30,7,21,77,8,17,94
4,45,85,56,84,43,41,71,43,27,26,...,54,37,1,40,7,17,26,12,71,98

In [13]:
"""エクセルデータをimport """

'エクセルデータをimport '

In [250]:
test_data = pd.read_excel('./data/sample_data.xlsx')
table = test_data["tables"]
test_data = test_data.drop("tables", axis=1)
print(test_data.shape)
test_data.head()

(54, 64)

,1,2,3,4,5,6,7,8,9,10,...,55,56,57,58,59,60,61,62,63,64
0,222,164,165,398,287,209,123,118,220,95,...,253,100,84,194,146,306,301,75,369,132
1,116,203,165,298,296,393,125,104,121,533,...,128,332,80,161,117,378,210,280,184,184
2,140,129,180,108,155,350,92,127,114,145,...,697,131,86,126,1077,223,139,56,165,787
3,254,797,503,299,85,160,109,287,185,172,...,234,146,171,311,245,262,298,122,116,83
4,98,292,332,376,127,95,121,198,187,206,...,246,194,107,199,121,233,934,155,104,186

In [251]:
column = 21
r = test_data.shape[1] - column 
print(column , r)

21 43

In [253]:
#g_data = pd.DataFrame()
#h_data = pd.DataFrame()
h_data = np.empty([1, r,1])
g_data = np.empty([1, r, column])
for index , row in test_data.iterrows():
    #male_dataset関数
    g, h = make_dataset(row)
    
    g_add = g.reshape((1, r,column))
    g_data = np.r_[g_data, g_add]
    
    h_add = h.reshape((1, r,1))
    h_data = np.r_[h_data, h_add]

g  = np.delete(g_data , 0, 0)
h  = np.delete(h_data , 0, 0)


np.save('./g_sample_data', g)
np.save('./h_sample_data', h)

In [254]:
g[0]

array([[ 222.,  164.,  165.,  398.,  287.,  209.,  123.,  118.,  220.,
          95.,  192.,  112.,  165.,  162.,  148.,  229.,  229.,  143.,
         280.,  155.,  499.],
       [ 164.,  165.,  398.,  287.,  209.,  123.,  118.,  220.,   95.,
         192.,  112.,  165.,  162.,  148.,  229.,  229.,  143.,  280.,
         155.,  499.,  116.],
       [ 165.,  398.,  287.,  209.,  123.,  118.,  220.,   95.,  192.,
         112.,  165.,  162.,  148.,  229.,  229.,  143.,  280.,  155.,
         499.,  116.,  196.],
       [ 398.,  287.,  209.,  123.,  118.,  220.,   95.,  192.,  112.,
         165.,  162.,  148.,  229.,  229.,  143.,  280.,  155.,  499.,
         116.,  196.,  114.],
       [ 287.,  209.,  123.,  118.,  220.,   95.,  192.,  112.,  165.,
         162.,  148.,  229.,  229.,  143.,  280.,  155.,  499.,  116.,
         196.,  114.,  218.],
       [ 209.,  123.,  118.,  220.,   95.,  192.,  112.,  165.,  162.,
         148.,  229.,  229.,  143.,  280.,  155.,  499.,  116.,  196.,
         114.,  218.,  413.],
       [ 123.,  118.,  220.,   95.,  192.,  112.,  165.,  162.,  148.,
         229.,  229.,  143.,  280.,  155.,  499.,  116.,  196.,  114.,
         218.,  413.,  241.],
       [ 118.,  220.,   95.,  192.,  112.,  165.,  162.,  148.,  229.,
         229.,  143.,  280.,  155.,  499.,  116.,  196.,  114.,  218.,
         413.,  241.,  116.],
       [ 220.,   95.,  192.,  112.,  165.,  162.,  148.,  229.,  229.,
         143.,  280.,  155.,  499.,  116.,  196.,  114.,  218.,  413.,
         241.,  116.,  275.],
       [  95.,  192.,  112.,  165.,  162.,  148.,  229.,  229.,  143.,
         280.,  155.,  499.,  116.,  196.,  114.,  218.,  413.,  241.,
         116.,  275.,  211.],
       [ 192.,  112.,  165.,  162.,  148.,  229.,  229.,  143.,  280.,
         155.,  499.,  116.,  196.,  114.,  218.,  413.,  241.,  116.,
         275.,  211.,  173.],
       [ 112.,  165.,  162.,  148.,  229.,  229.,  143.,  280.,  155.,
         499.,  116.,  196.,  114.,  218.,  413.,  241.,  116.,  275.,
         211.,  173.,   92.],
       [ 165.,  162.,  148.,  229.,  229.,  143.,  280.,  155.,  499.,
         116.,  196.,  114.,  218.,  413.,  241.,  116.,  275.,  211.,
         173.,   92.,  221.],
       [ 162.,  148.,  229.,  229.,  143.,  280.,  155.,  499.,  116.,
         196.,  114.,  218.,  413.,  241.,  116.,  275.,  211.,  173.,
          92.,  221.,  137.],
       [ 148.,  229.,  229.,  143.,  280.,  155.,  499.,  116.,  196.,
         114.,  218.,  413.,  241.,  116.,  275.,  211.,  173.,   92.,
         221.,  137.,  142.],
       [ 229.,  229.,  143.,  280.,  155.,  499.,  116.,  196.,  114.,
         218.,  413.,  241.,  116.,  275.,  211.,  173.,   92.,  221.,
         137.,  142.,  195.],
       [ 229.,  143.,  280.,  155.,  499.,  116.,  196.,  114.,  218.,
         413.,  241.,  116.,  275.,  211.,  173.,   92.,  221.,  137.,
         142.,  195.,  243.],
       [ 143.,  280.,  155.,  499.,  116.,  196.,  114.,  218.,  413.,
         241.,  116.,  275.,  211.,  173.,   92.,  221.,  137.,  142.,
         195.,  243.,  102.],
       [ 280.,  155.,  499.,  116.,  196.,  114.,  218.,  413.,  241.,
         116.,  275.,  211.,  173.,   92.,  221.,  137.,  142.,  195.,
         243.,  102.,  131.],
       [ 155.,  499.,  116.,  196.,  114.,  218.,  413.,  241.,  116.,
         275.,  211.,  173.,   92.,  221.,  137.,  142.,  195.,  243.,
         102.,  131.,  244.],
       [ 499.,  116.,  196.,  114.,  218.,  413.,  241.,  116.,  275.,
         211.,  173.,   92.,  221.,  137.,  142.,  195.,  243.,  102.,
         131.,  244., 1334.],
       [ 116.,  196.,  114.,  218.,  413.,  241.,  116.,  275.,  211.,
         173.,   92.,  221.,  137.,  142.,  195.,  243.,  102.,  131.,
         244., 1334.,  160.],
       [ 196.,  114.,  218.,  413.,  241.,  116.,  275.,  211.,  173.,
          92.,  221.,  137.,  142.,  195.,  243.,  102.,  131.,  244.,
        1334.,  160.,  152.],
       [ 114.,  218.,  413.,  241.,  116.,  275.,  211.,  173.,   92.,
         221.,  137.,  142.,  195.,  243.,  102.,  131.,  244., 1334.,
         160.,  152.,  129.],
       [ 218.,  413.,  241.,  116.,  275.,  211.,  173.,   92.,  221.,
         137.,  142.,  195.,  243.,  102.,  131.,  244., 1334.,  160.,
         152.,  129.,  161.],
       [ 413.,  241.,  116.,  275.,  211.,  173.,   92.,  221.,  137.,
         142.,  195.,  243.,  102.,  131.,  244., 1334.,  160.,  152.,
         129.,  161.,  551.],
       [ 241.,  116.,  275.,  211.,  173.,   92.,  221.,  137.,  142.,
         195.,  243.,  102.,  131.,  244., 1334.,  160.,  152.,  129.,
         161.,  551.,  211.],
       [ 116.,  275.,  211.,  173.,   92.,  221.,  137.,  142.,  195.,
         243.,  102.,  131.,  244., 1334.,  160.,  152.,  129.,  161.,
         551.,  211.,  258.],
       [ 275.,  211.,  173.,   92.,  221.,  137.,  142.,  195.,  243.,
         102.,  131.,  244., 1334.,  160.,  152.,  129.,  161.,  551.,
         211.,  258.,  441.],
       [ 211.,  173.,   92.,  221.,  137.,  142.,  195.,  243.,  102.,
         131.,  244., 1334.,  160.,  152.,  129.,  161.,  551.,  211.,
         258.,  441.,  695.],
       [ 173.,   92.,  221.,  137.,  142.,  195.,  243.,  102.,  131.,
         244., 1334.,  160.,  152.,  129.,  161.,  551.,  211.,  258.,
         441.,  695.,  273.],
       [  92.,  221.,  137.,  142.,  195.,  243.,  102.,  131.,  244.,
        1334.,  160.,  152.,  129.,  161.,  551.,  211.,  258.,  441.,
         695.,  273.,  115.],
       [ 221.,  137.,  142.,  195.,  243.,  102.,  131.,  244., 1334.,
         160.,  152.,  129.,  161.,  551.,  211.,  258.,  441.,  695.,
         273.,  115.,  132.],
       [ 137.,  142.,  195.,  243.,  102.,  131.,  244., 1334.,  160.,
         152.,  129.,  161.,  551.,  211.,  258.,  441.,  695.,  273.,
         115.,  132.,  413.],
       [ 142.,  195.,  243.,  102.,  131.,  244., 1334.,  160.,  152.,
         129.,  161.,  551.,  211.,  258.,  441.,  695.,  273.,  115.,
         132.,  413.,  253.],
       [ 195.,  243.,  102.,  131.,  244., 1334.,  160.,  152.,  129.,
         161.,  551.,  211.,  258.,  441.,  695.,  273.,  115.,  132.,
         413.,  253.,  100.],
       [ 243.,  102.,  131.,  244., 1334.,  160.,  152.,  129.,  161.,
         551.,  211.,  258.,  441.,  695.,  273.,  115.,  132.,  413.,
         253.,  100.,   84.],
       [ 102.,  131.,  244., 1334.,  160.,  152.,  129.,  161.,  551.,
         211.,  258.,  441.,  695.,  273.,  115.,  132.,  413.,  253.,
         100.,   84.,  194.],
       [ 131.,  244., 1334.,  160.,  152.,  129.,  161.,  551.,  211.,
         258.,  441.,  695.,  273.,  115.,  132.,  413.,  253.,  100.,
          84.,  194.,  146.],
       [ 244., 1334.,  160.,  152.,  129.,  161.,  551.,  211.,  258.,
         441.,  695.,  273.,  115.,  132.,  413.,  253.,  100.,   84.,
         194.,  146.,  306.],
       [1334.,  160.,  152.,  129.,  161.,  551.,  211.,  258.,  441.,
         695.,  273.,  115.,  132.,  413.,  253.,  100.,   84.,  194.,
         146.,  306.,  301.],
       [ 160.,  152.,  129.,  161.,  551.,  211.,  258.,  441.,  695.,
         273.,  115.,  132.,  413.,  253.,  100.,   84.,  194.,  146.,
         306.,  301.,   75.],
       [ 152.,  129.,  161.,  551.,  211.,  258.,  441.,  695.,  273.,
         115.,  132.,  413.,  253.,  100.,   84.,  194.,  146.,  306.,
         301.,   75.,  369.]])

In [256]:
g.shape

(54, 43, 21)